### ISSUE TITLE
CUDA Error:     File:       force/potential.cu     Line:       332     Error code: 700     Error text: an illegal memory access was encountered

### ISSUE THREAD

**Issue by why626726-cell** [brucefan1983/GPUMD#1210]
[nep_gen160000.txt](https://github.com/user-attachments/files/22915417/nep_gen160000.txt)

[model.xyz.txt](https://github.com/user-attachments/files/22915486/model.xyz.txt)

[run.in.txt](https://github.com/user-attachments/files/22915500/run.in.txt)

Dear GPUMD developers,
I’m currently using GPUMD to perform molecular dynamics simulations with a NEP potential trained by the built-in NEP training module.Both the training and MD simulations were carried out within GPUMD.
However, I encountered a CUDA error (   
 File:       force/potential.cu
    Line:       332
    Error code: 700
    Error text: an illegal memory access was encountered)  during the MD run under the following conditions:
The simulation runs normally when I use the built-in general potential nep89 with the same structure file (model.xyz);The simulation also runs normally when I use my trained NEP potential with a small model (<100 atoms);
The error occurs only when I use my trained NEP potential with a larger model(model.xyz).I've already tested this model and found it to be reasonable.
Could you please help me identify the possible reason for this issue?I have attached the following files（potential,model.xyz,run.in) for your reference.Thank you very much for your time.

**Comment by tang070205** [comment]
From my point of view, you can observe the contents of the `neighbour.out` file, or again try to change the cutoff of training, like 6 4.

**Comment by ashwani12-cmd** [comment]
I am facing the same issue.


CUDA Error:
    File:       ./utilities/gpu_vector.cuh
    Line:       155
    Error code: 700
    Error text: an illegal memory access was encountered
srun: error: rmgpu002: task 0: Exited with exit code 1


nep3 3 Mg Bi Sb 
cutoff 6 4 41 12
n_max 10 8
basis_size 8 8
l_max 4 2 0
ANN 50 0
  1.2294444e-03
 -2.5083107e-04
 -2.6304692e-03
  3.5682712e-02
 -3.1574929e-01
  6.7569799e-04
  1.1559746e-01
  5.1712192e-04
 -1.3070055e+00
  2.4768343e-02
  2.6233798e-02
  8.0948288e-05
  1.9798407e-03
  1.5963943e-03
 -3.2475889e-03
 -4.1444381e-03
 -1.1184504e-03
 -5.8116806e-03
 -4.0973946e-03
 -5.6690293e-05
  9.5998956e-04
 -2.6075609e-03
  1.1196828e-03
 -4.0734429e-03
 -4.4933911e-03
 -1.2544234e-03
 -1.1590783e-03
 -1.1767935e-02
 -1.1736527e-03
 -5.2746204e-03
  2.2865477e-04
 -5.4214085e-03
 -5.1578376e-03
 -5.6628319e-03
 -1.8308641e-01
  2.4195067e-03
  1.1042714e-03
 -2.3189124e-03
 -1.0687751e-04
 -3.3076056e-03
 -1.5206279e-03
  1.7313387e-03
 -3.1813935e-04
 -7.0373430e-03
  5.0472808e-03
  1.6301499e-03
 -6.4374669e-04
 -7.3320675e-03
  6.5511623e-03

**Comment by tang070205** [comment]
> I am facing the same issue.
> 
> CUDA Error: File: ./utilities/gpu_vector.cuh Line: 155 Error code: 700 Error text: an illegal memory access was encountered srun: error: rmgpu002: task 0: Exited with exit code 1
> 
> nep3 3 Mg Bi Sb cutoff 6 4 41 12 n_max 10 8 basis_size 8 8 l_max 4 2 0 ANN 50 0 1.2294444e-03 -2.5083107e-04 -2.6304692e-03 3.5682712e-02 -3.1574929e-01 6.7569799e-04 1.1559746e-01 5.1712192e-04 -1.3070055e+00 2.4768343e-02 2.6233798e-02 8.0948288e-05 1.9798407e-03 1.5963943e-03 -3.2475889e-03 -4.1444381e-03 -1.1184504e-03 -5.8116806e-03 -4.0973946e-03 -5.6690293e-05 9.5998956e-04 -2.6075609e-03 1.1196828e-03 -4.0734429e-03 -4.4933911e-03 -1.2544234e-03 -1.1590783e-03 -1.1767935e-02 -1.1736527e-03 -5.2746204e-03 2.2865477e-04 -5.4214085e-03 -5.1578376e-03 -5.6628319e-03 -1.8308641e-01 2.4195067e-03 1.1042714e-03 -2.3189124e-03 -1.0687751e-04 -3.3076056e-03 -1.5206279e-03 1.7313387e-03 -3.1813935e-04 -7.0373430e-03 5.0472808e-03 1.6301499e-03 -6.4374669e-04 -7.3320675e-03 6.5511623e-03

From the normal point of view of analysis, you this case probability potential function problem, but there is a point, you use NEP3 is there any need, now NEP4 for multi-element fit will be better, so it is best to use NEP4 to training!

**Comment by ashwani12-cmd** [comment]
**Script**

potential ./nep_y2025_m10_d18_h18_m55_s49_generation200000.txt 0

minimize sd 1e-08 10000


velocity 300
time_step 1
ensemble nvt_nhc 300 300 100
neighbor 100
dump_thermo 1000
run 100000  # Equilibration



**Potential initial lines**

nep4 3 Mg Bi Sb
cutoff 7 4 60 12
n_max 10 8
basis_size 8 8
l_max 4 2 0
ANN 50 0
-6.7878467e-01
-5.0169015e-01
... 

AT 50 K Temp in nvt_nhc is stable but 300 K in nvt_nhc is unstable same error CUDA Error: 

File: ./utilities/gpu_vector.cuh Line: 155 Error code: 700 Error text: an illegal memory access was encountered srun: error: rmgpu002: task 0: Exited with exit code 1

**Comment by ashwani12-cmd** [comment]
Hey all,
I’m running GPUMD with NEP4 (Mg3Bi2, 2500 atoms, cutoff 7 4, neuron 50) and encountering an illegal memory access error (CUDA 700) at 300 K, causing a crash, while it runs smoothly at 50 K. I tried adjusting the cutoff from 5.5 to 7 Å, but the error persists with no improvement.
Any ideas? Could the increased dynamics at higher temperatures be triggering this issue in the NEP4 ANN? I’m planning to retrain with neuron 20-30, n_max 8 6, basis_size 6 6, batch 500, lambda_v 0.1, gelu activation, and 100k generations. Suggestions or known cases?

potential ./nep_y2025_m10_d19_h06_m25_s57_generation200000.txt  0


minimize fire 1.0e-5 10000 1

ensemble    nve
time_step   0
dump_xyz    -1 0 1 relaxed.xyz
run         1

# Heat Step (100 ps)
velocity 50
time_step 1
ensemble nvt_nhc 50 50 200
dump_xyz    -1 0 10000 nvt_run.xyz
dump_thermo 10000
run 100000

 
# HNEMA Step (20 ns)
ensemble nvt_nhc 50 50 200
dump_thermo 10000
#compute_hnemd 1000 0 1e-05 0
compute_hnema 8  10000  1e-05 0 0 1 7500  f_bin_size 1 
compute_shc 2 250 0 1000 12
run 20000000

**Comment by brucefan1983** [comment]
The most probable reason is that the training data are not sufficient. Could you describe the training dataset in some detail?

**Comment by ashwani12-cmd** [comment]
I used this 

NepTrain perturb ./POSCAR --num 500 - -cell 0.00  -d 0.1 , means generated 500 structures with 0.1 A atomic displacement without any change in lattice parameter.

**Comment by brucefan1983** [comment]
OK, could you show a parity plot of force training results?

**Comment by ashwani12-cmd** [comment]
Test Error

<img width="1613" height="425" alt="Image" src="https://github.com/user-attachments/assets/cccbfb57-5427-4bf5-b981-20760883647d" />

Train Error

<img width="1090" height="845" alt="Image" src="https://github.com/user-attachments/assets/61cf703c-f930-4239-a47d-dea6bd7df22a" />

**Comment by brucefan1983** [comment]
Your dataset has two problems:

1) The force range is too small. This means that, if you want to use the position pertubation method in NepTrain, you need to consider larger displacement, such as 0.2 A. Also you can consider adding box perturbation as well.

2) The absolute energy of your training dataset is too large. I think you used QE or CP2K, and in this case, it is better to shift the energy to about zero. This will significantly speed up the convergence of the training and probably leads to better model.

**Comment by brucefan1983** [comment]
Any update? Usually this is not due to bug(s) in GPUMD, but means the trained NEP model is still not good enough.

**Comment by ashwani12-cmd** [comment]
Yes, it turned out to be a force-related issue. I increased the atomic displacement, and the problem disappeared. Interestingly, I had trained an MTP model on the same dataset, and in LAMMPS I encountered atom lost errors instead of the illegal memory access error that GPUMD reported. I'm still using GPUMD, and it’s running fine now. Initially, I had set the displacement to 0.2, which worked up to around 400 K, but the illegal memory access error reappeared at higher temperatures. After increasing it to 0.3, the simulations are stable up to 700 K.

**Comment by brucefan1983** [comment]
LAMMPS and GPUMD report errors in different ways. Losing atoms in LAMMPS and illegal memory access in GPUMD are usually caused by the same issues, such as an inadequate potential or a very bad initial simulation model.

It seems you mainly used atom position perturbation to generate training data. That is good in the beginning, but you might also need to add some training structures based on active learning.

Anyway, I think this issue can be closed.
