### ISSUE TITLE
Failed to run GPUMD with DP

### ISSUE THREAD

**Issue by ShuSOfficial** [brucefan1983/GPUMD#1218]
Here are my installation commands:

``` shell
module load cuda/11.8.0
conda create -n dpgpumd python=3.10 cudatoolkit=11.8 tensorflow=2.13 cmake -c conda-forge
conda activate dpgpumd
```

I followed the tutorial on the website:

``` shell
cmake -DENABLE_TENSORFLOW=TRUE -DUSE_CUDA_TOOLKIT=TRUE -DCMAKE_INSTALL_PREFIX="/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/deepmd-kit-3.0.3/source/build/install" -DUSE_TF_PYTHON_LIBS=TRUE ../
make -j & make install
```

``` shell
export deepmd_source_dir=/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/deepmd-kit-3.0.3/source/build/install
```

``` shell
CFLAGS = -std=c++14 -O3 $(CUDA_ARCH) -DUSE_TENSORFLOW
endif
INC = -I./
INC += -I${deepmd_source_dir}/include/deepmd
LDFLAGS = 
LIBS = -lcublas -lcusolver
LIBS += -L${deepmd_source_dir}/lib -ldeepmd_cc
```

I use depend-kit=3.0.3 and GPUMD=4.4.0. And the installation process completed without any errors.

Before running, I also added the install path to ~/.bashrc:

``` shell
# DP+GPUMD
installpath="/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/deepmd-kit-3.0.3/source/build/install"
export LD_LIBRARY_PATH=${installpath}/lib:$LD_LIBRARY_PATH
``` 

However, when I use the command as followed to run GPUMD:

``` shell
module load cuda/11.8.0
export TF_ENABLE_ONEDNN_OPTS=0
export TF_INTER_OP_PARALLELISM_THREADS=1
export TF_INTRA_OP_PARALLELISM_THREADS=1
export OMP_NUM_THREADS=1

# 你的库路径设置是正确的
installpath="/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/deepmd-kit-3.0.3/source/build/install"
#export LD_LIBRARY_PATH=${installpath}/lib:$LD_LIBRARY_PATH


# 运行前可以验证库路径
echo "当前库搜索路径: $LD_LIBRARY_PATH"
echo "DeepMD库目录内容:"
ls -la ${installpath}/lib/


FilePath="/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/GPUMD-4.4/src"
${FilePath}/gpumd > log.gpumd
```

A CUDA error occurred:

``` shell
当前库搜索路径: /opt/devtools/nvidia/cuda-11.8.0/lib64:/home/liushiLab/zhouwenjie/software/GPUMD-4.4.0/deepmd-kit-3.0.3/source/build/install/lib:
DeepMD库目录内容:
总计 10976
drwxr-xr-x 3 zhouwenjie liulab      10 10月 30 10:22 .
drwxr-xr-x 6 zhouwenjie liulab       4 10月 30 10:22 ..
drwxr-xr-x 3 zhouwenjie liulab       1 10月 30 10:22 cmake
lrwxrwxrwx 1 zhouwenjie liulab      15 10月 30 10:22 libdeepmd_cc_low.so -> libdeepmd_cc.so
-rw-r--r-- 1 zhouwenjie liulab  842096 10月 30 10:21 libdeepmd_cc.so
-rw-r--r-- 1 zhouwenjie liulab  215784 10月 30 10:21 libdeepmd_c.so
-rw-r--r-- 1 zhouwenjie liulab  110776 10月 30 10:21 libdeepmd_dyn_cudart.so
-rw-r--r-- 1 zhouwenjie liulab  152760 10月 30 10:21 libdeepmd_gromacs.so
-rw-r--r-- 1 zhouwenjie liulab   49000 10月 30 10:21 libdeepmd_ipi.so
-rw-r--r-- 1 zhouwenjie liulab 7809624 10月 30 10:21 libdeepmd_op_cuda.so
-rw-r--r-- 1 zhouwenjie liulab 1728512 10月 30 10:21 libdeepmd_op.so
-rw-r--r-- 1 zhouwenjie liulab  326456 10月 30 10:21 libdeepmd.so
2025-10-30 10:29:59.537584: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-30 10:29:59.570095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9731 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:d5:00.0, compute capability: 7.5
2025-10-30 10:29:59.595462: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
CUDA Error:
    File:       ./utilities/gpu_vector.cuh
    Line:       84
    Error code: 2
    Error text: out of memory
```

**Comment by MoseyQAQ** [comment]
Hi, how many atoms are in your system? I have tested a system with 10,800 atoms on 2080Ti, and no OOM was detected.

**Comment by brucefan1983** [comment]
could you provide more details? how many atoms?

**Comment by ShuSOfficial** [comment]
I test the example of "water_mds". It contains 1536 atoms.

**Comment by brucefan1983** [comment]
That should be ok for DP with 2080ti you used, but I am also not sure what is the possible reason for the error.

**Comment by ShuSOfficial** [comment]
Maybe I have found the reason. The tutorial on the website asked me to install the cudatool-kit, but actually, I have loaded the cuda=11.8. So I try to use pip to avoid the installation of cudatool-kit. Now, I can successfully run the example.

**Comment by brucefan1983** [comment]
OK, so it might be a CUDA toolkit version issue. You can close if you think this issue is solved.

**Comment by ShuSOfficial** [comment]
Sorry, when I resubmit the batch file, the same error occurred. And I find that, the tensorflow installed with pip can not find the lib of CUDA, so the computational efficiency is very slow. But, this error (out of memory) appears to be an issue with the related software calling the driver, rather than a bug in GPUMD itself. Therefore, I will close this issue.

**Comment by brucefan1983** [comment]
Thanks for sharing these. These are the exact motivations for me to stick to native CUDA programming (without external dependence) for the majority of GPUMD.
